create database RH_INFO;

USE RH_INFO;

CREATE TABLE TB_COLABORADORES(
ID BIGINT AUTO_INCREMENT,
primary key (id),
NOME VARCHAR(255),
IDADE INT,
FUNCAO VARCHAR(255),
SEXO VARCHAR(255),
SALARIO decimal
);
