CREATE DATABASE IF NOT EXISTS /*IF NOT EXISTS é para verificar se tem a tabela ou a database*/ DB_RH;

USE DB_RH;/*OBRIGATORIO PARA USAR O BANCO DE DADOS*/

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME CHAR(255) NOT NULL		/* NOT NULL SIGNIFICA QUE AQUELA PARTE
PRECICA SER OBRIGATORIA*/,
NASCIMENTO INT,
SALARIO DECIMAL,
CARGO CHAR(255),
primary key (id)
);


SELECT * FROM TB_FUNCIONARIOS;
SELECT * FROM TB_FUNCIONARIOS WHERE NOME LIKE "%S%";
/*SELECT * FROM TB_FUNCIONARIOS WHERE NOME = "ALE";*/
/*SELECT * FROM TB_FUNCIONARIOS WHERE ID = 5;*/
/*SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO > 1000;*/

INSERT INTO TB_FUNCIONARIOS (NOME, NASCIMENTO, SALARIO, CARGO) VALUES ("ALESSANDRO",27-06-1998, 1000, "DEV");
INSERT INTO TB_FUNCIONARIOS (NOME, NASCIMENTO, SALARIO, CARGO) VALUES ("ALE",98, 1000, "PROF");
INSERT INTO TB_FUNCIONARIOS (NOME, NASCIMENTO, SALARIO, CARGO) VALUES ("SANDRO",27, 1000, "DEV");